services:
  app:
    build: .
    container_name: gym_app
    restart: unless-stopped
    ports:
      - "3003:3000"
    environment:
      - AUTH_USER=eduardosouzadev
      - AUTH_PASS=6JVMmoyrWXSp1o_AEQ-6Jw
      - SESSION_SECRET=WsEVYEHcO73cGoY6yhJXIit5pa0IUzPIY1iaToKyF50
    volumes:
      - gym_data:/app/data

volumes:
  gym_data:
